"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { createClient } from "@/lib/supabase/client"
import { VariantBuilder } from "@/components/admin/VariantBuilder"

interface ProductFormProps {
  initialData?: any;
}

export default function ProductForm({ initialData }: ProductFormProps) {
  const router = useRouter()
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  
  // 1. New state to hold the variants generated by the builder
  const [variants, setVariants] = useState<any[]>([])

  const [form, setForm] = useState({
    name: initialData?.name || "",
    slug: initialData?.slug || "",
    description: initialData?.description || "",
    short_description: initialData?.short_description || "",
    price: initialData?.price?.toString() || "",
    compare_at_price: initialData?.compare_at_price?.toString() || "",
    category: initialData?.category || "training",
    subcategory: initialData?.subcategory || "",
    brand: initialData?.brand || "Zapatos Cave",
    sku: initialData?.sku || "",
    stock_quantity: initialData?.stock_quantity?.toString() || "0",
    is_active: initialData?.is_active ?? true,
    is_featured: initialData?.is_featured ?? false,
    volume: initialData?.volume || "",
  })

  const [imageUrls, setImageUrls] = useState<string[]>(initialData?.images?.map((img: any) => img.url) || [""])
  const [personalityTags, setPersonalityTags] = useState<string[]>(initialData?.personality_tags || [])

  const updateField = (field: string, value: string | boolean) => {
    setForm((prev) => ({ ...prev, [field]: value }))
    if (field === "name" && !initialData && !form.slug) {
      const slug = (value as string).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")
      setForm((prev) => ({ ...prev, slug }))
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)
    setIsLoading(true)

    const supabase = createClient()
    const images = imageUrls.filter((url) => url.trim()).map((url) => ({ url: url.trim() }))

    const payload = {
      ...form,
      price: parseFloat(form.price),
      compare_at_price: form.compare_at_price ? parseFloat(form.compare_at_price) : null,
      stock_quantity: parseInt(form.stock_quantity) || 0,
      images,
      personality_tags: personalityTags,
    }

    let productResult;
    
    // 2. We use .select().single() to get the ID of the product we just created
    if (initialData?.id) {
      productResult = await supabase.from("products").update(payload).eq("id", initialData.id).select().single()
    } else {
      productResult = await supabase.from("products").insert(payload).select().single()
    }

    if (productResult.error) {
      setError(productResult.error.message)
      setIsLoading(false)
      return
    }

    // 3. Save the Variants to the product_variants table
    if (productResult.data && variants.length > 0) {
      const variantsPayload = variants.map(v => ({
        product_id: productResult.data.id,
        sku: v.sku || `${form.slug}-${v.option1.value}`,
        price: parseFloat(v.price) || payload.price,
        stock_quantity: parseInt(v.stock) || 0,
        option1_name: v.option1.name,
        option1_value: v.option1.value,
        option2_name: v.option2?.name || null,
        option2_value: v.option2?.value || null,
        option3_name: v.option3?.name || null,
        option3_value: v.option3?.value || null,
        variant_image: v.image_url || null // This will handle the color-specific images
      }))

      const variantResult = await supabase.from("product_variants").insert(variantsPayload)
      
      if (variantResult.error) {
        console.error("Error saving variants:", variantResult.error.message)
      }
    }

    router.push("/admin/products")
    router.refresh()
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-8">
      {error && <div className="p-4 bg-red-50 text-red-700 rounded-lg border border-red-200">{error}</div>}
      
      <div className="bg-white p-8 rounded-none border border-black/10 space-y-6">
        <h2 className="text-xs font-bold uppercase tracking-[0.2em] border-b pb-4 mb-4">Product Specifications</h2>
        {/* ... (Existing Inputs for Name, Slug, Description) ... */}
        <div className="space-y-2">
          <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500">Product Name</label>
          <Input value={form.name} onChange={(e) => updateField("name", e.target.value)} required />
        </div>
        <div className="space-y-2">
          <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500">URL Slug</label>
          <Input value={form.slug} onChange={(e) => updateField("slug", e.target.value)} required />
        </div>
        <div className="space-y-2">
          <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500">Full Description</label>
          <textarea 
            className="w-full border border-black/10 p-3 text-sm min-h-[120px]" 
            value={form.description}
            onChange={(e) => updateField("description", e.target.value)}
          />
        </div>
      </div>

      {/* Pricing & Stock Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 bg-white p-8 border border-black/10">
         <div className="space-y-2">
           <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500">Base Price (Ksh)</label>
           <Input type="number" value={form.price} onChange={(e) => updateField("price", e.target.value)} />
         </div>
         <div className="space-y-2">
           <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500">Total Stock</label>
           <Input type="number" value={form.stock_quantity} onChange={(e) => updateField("stock_quantity", e.target.value)} />
         </div>
      </div>

      {/* Variant Builder */}
      <div className="mt-8">
        <VariantBuilder onVariantsChange={(v) => setVariants(v)} />
      </div>

      <Button 
        type="submit" 
        disabled={isLoading} 
        className="w-full bg-black text-white hover:bg-gray-800 rounded-none h-14 uppercase tracking-[0.3em] font-bold text-xs"
      >
        {isLoading ? "Synchronizing..." : initialData ? "Update Gear" : "Launch Product"}
      </Button>
    </form>
  )
}