export interface ShippingLocation {
  id: string;
  name: string;
  eta: string;
  maxWeightKg: number;
  price: number;
}

export const kenyanShippingRates: ShippingLocation[] = [
  { id: "ahero_overnight", name: "Ahero (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 350 },
  { id: "athi_river_1_2days", name: "Athi River (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 400 },
  { id: "awendo_overnight", name: "Awendo (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 400 },
  { id: "baraton_overnight", name: "Baraton (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 450 },
  { id: "bomet_overnight", name: "Bomet (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 340 },
  { id: "bondo_overnight", name: "Bondo (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 500 },
  { id: "bungoma_1_2days", name: "Bungoma (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 400 },
  { id: "burnt_forest_1_2days", name: "Burnt Forest (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 450 },
  { id: "busia_overnight", name: "Busia (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 550 },
  { id: "chogoria_2_3days", name: "Chogoria (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 750 },
  { id: "chuka_2_3days", name: "Chuka (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 650 },
  { id: "chwele_1_2days", name: "Chwele (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 400 },
  { id: "diani_2days", name: "Diani (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 900 },
  { id: "eldama_ravine_overnight", name: "Eldama Ravine (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 300 },
  { id: "eldoret_overnight", name: "Eldoret (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 330 },
  { id: "eldoret_sameday", name: "Eldoret (via Cross Road Same Day)", eta: "Same Day", maxWeightKg: 10, price: 400 },
  { id: "emali_2days", name: "Emali (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 750 },
  { id: "embu_2_3days", name: "Embu (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 650 },
  { id: "engineer_1_2days", name: "Engineer (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 330 },
  { id: "garissa_2days", name: "Garissa (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 900 },
  { id: "garsen_2days", name: "Garsen (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 1800 },
  { id: "gatundu_1_2days", name: "Gatundu (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 450 },
  { id: "gilgil_overnight", name: "Gilgil (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 300 },
  { id: "gilgil_matatu", name: "Gilgil (via Matatu 2-3hrs)", eta: "2-3 Hours", maxWeightKg: 10, price: 300 },
  { id: "githunguri_1_2days", name: "Githunguri (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 450 },
  { id: "hola_tana_river_2days", name: "Hola Tana River (2 Days)", eta: "2 Days", maxWeightKg: 3, price: 1440 },
  { id: "homabay_overnight", name: "Homabay (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 420 },
  { id: "homabay_easycoach", name: "Homabay (via Easy Coach)", eta: "Overnight", maxWeightKg: 10, price: 400 },
  { id: "isebania_2_3days", name: "Isebania (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 550 },
  { id: "isinya_2days", name: "Isinya (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 750 },
  { id: "isiolo_2_3days", name: "Isiolo (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 750 },
  { id: "isiolo_meiso", name: "Isiolo (Meiso Sacco)", eta: "1-2 Days", maxWeightKg: 5, price: 550 },
  { id: "iten_1_2days", name: "Iten (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 330 },
  { id: "juja_2_3days", name: "Juja (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 520 },
  { id: "kabarnet_1_2days", name: "Kabarnet (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 330 },
  { id: "kagio_2_3days", name: "Kagio (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 650 },
  { id: "kahawa_overnight", name: "Kahawa Wendani/Sukari (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 350 },
  { id: "kajiado_1_2days", name: "Kajiado (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 750 },
  { id: "kakamega_overnight", name: "Kakamega (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 420 },
  { id: "kakamega_easycoach", name: "Kakamega (via Easy Coach)", eta: "Overnight", maxWeightKg: 7, price: 400 },
  { id: "kakuma_turkrift", name: "Kakuma Town (via TurkRift)", eta: "2-3 Days", maxWeightKg: 10, price: 600 },
  { id: "kakuma_standard", name: "Kakuma Town (Standard)", eta: "2-3 Days", maxWeightKg: 5, price: 2500 },
  { id: "kangari_2_3days", name: "Kangari (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 570 },
  { id: "kangema_2_3days", name: "Kangema (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 600 },
  { id: "kangundo_1_2days", name: "Kangundo (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 550 },
  { id: "kapenguria_1_2days", name: "Kapenguria (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 380 },
  { id: "kapsabet_1_2days", name: "Kapsabet (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 380 },
  { id: "karatina_2_3days", name: "Karatina (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 650 },
  { id: "kehancha_overnight", name: "Kehancha (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 540 },
  { id: "kendubay_overnight", name: "Kendubay (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 450 },
  { id: "kericho_overnight", name: "Kericho (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 340 },
  { id: "kericho_wish", name: "Kericho (via Wish Vehicles 2-3hrs)", eta: "2-3 Hours", maxWeightKg: 10, price: 350 },
  { id: "keroka_overnight", name: "Keroka (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 400 },
  { id: "kerugoya_2_3days", name: "Kerugoya (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 650 },
  { id: "kiambu_1_2days", name: "Kiambu Town (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 450 },
  { id: "kibwezi_1_2days", name: "Kibwezi (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 750 },
  { id: "kiganjo_2_3days", name: "Kiganjo (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 650 },
  { id: "kijabe_1_2days", name: "Kijabe (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 300 },
  { id: "kikuyu_1_2days", name: "Kikuyu (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 450 },
  { id: "kilgoris_overnight", name: "Kilgoris (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 400 },
  { id: "kilifi_2days", name: "Kilifi (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 950 },
  { id: "kilifi_bus", name: "Kilifi (via Bus)", eta: "1-2 Days", maxWeightKg: 10, price: 500 },
  { id: "kimana_naekana", name: "Kimana (via Naekana Sacco)", eta: "1-2 Days", maxWeightKg: 10, price: 500 },
  { id: "kimilili_1_2days", name: "Kimilili (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 400 },
  { id: "kiserian_overnight", name: "Kiserian (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 450 },
  { id: "kisii_overnight", name: "Kisii (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 350 },
  { id: "kisumu_overnight", name: "Kisumu (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 350 },
  { id: "kisumu_matatu", name: "Kisumu (via Matatu 4hrs)", eta: "4 Hours", maxWeightKg: 10, price: 400 },
  { id: "kitale_1_2days", name: "Kitale (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 380 },
  { id: "kitale_kangaroo", name: "Kitale (Kangaroo Shuttle)", eta: "Same Day", maxWeightKg: 10, price: 400 },
  { id: "kitengela_overnight", name: "Kitengela (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 450 },
  { id: "kitui_1_2days", name: "Kitui (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 600 },
  { id: "kutus_2_3days", name: "Kutus (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 600 },
  { id: "lamu_air", name: "Lamu (By Air)", eta: "2 Days", maxWeightKg: 5, price: 2200 },
  { id: "lamu_bus", name: "Lamu (via Bus 2-3days)", eta: "2-3 Days", maxWeightKg: 5, price: 500 },
  { id: "likoni_bus", name: "Likoni (Chania Genesis Bus)", eta: "1-2 Days", maxWeightKg: 10, price: 500 },
  { id: "limuru_overnight", name: "Limuru (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 300 },
  { id: "litein_overnight", name: "Litein (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 340 },
  { id: "lodwar_air", name: "Lodwar (By Air)", eta: "1-2 Days", maxWeightKg: 1.5, price: 1800 },
  { id: "lodwar_shuttle", name: "Lodwar (Via TurkRift Shuttle)", eta: "2-3 Days", maxWeightKg: 10, price: 500 },
  { id: "lokichogio_air", name: "Lokichogio (By Air)", eta: "1-2 Days", maxWeightKg: 5, price: 1800 },
  { id: "londiani_overnight", name: "Londiani (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 340 },
  { id: "luanda_overnight", name: "Luanda (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 560 },
  { id: "lugari_1_2days", name: "Lugari (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 400 },
  { id: "machakos_1_2days", name: "Machakos (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 560 },
  { id: "makindu_1_2days", name: "Makindu (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 760 },
  { id: "makutano_2_3days", name: "Makutano (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 760 },
  { id: "makuyu_2_3days", name: "Makuyu (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 560 },
  { id: "malaba_1_2days", name: "Malaba (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 400 },
  { id: "malindi_2days", name: "Malindi (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 1000 },
  { id: "malindi_bus", name: "Malindi (Modern Coast 2-3days)", eta: "2-3 Days", maxWeightKg: 5, price: 550 },
  { id: "maralal_1_2days", name: "Maralal (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 1050 },
  { id: "mariakani_bus", name: "Mariakani (via Bus 1-2days)", eta: "1-2 Days", maxWeightKg: 10, price: 500 },
  { id: "mariakani_standard", name: "Mariakani (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 880 },
  { id: "marsabit_2_3days", name: "Marsabit (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 1100 },
  { id: "maseno_overnight", name: "Maseno (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 360 },
  { id: "maseno_easycoach", name: "Maseno (via Easy Coach)", eta: "Overnight", maxWeightKg: 10, price: 400 },
  { id: "masii_1_2days", name: "Masii (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 560 },
  { id: "matuu_2_3days", name: "Matuu (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 560 },
  { id: "maua_2_3days", name: "Maua (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 780 },
  { id: "mbale_overnight", name: "Mbale (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 420 },
  { id: "mbale_bus", name: "Mbale (via Easy Coach/Guardian)", eta: "Overnight", maxWeightKg: 10, price: 400 },
  { id: "mbita_overnight", name: "Mbita (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 420 },
  { id: "meru_2days", name: "Meru (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 760 },
  { id: "meru_menachi", name: "Meru (via Menachi Sacco)", eta: "Same Day", maxWeightKg: 10, price: 500 },
  { id: "migori_overnight", name: "Migori (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 400 },
  { id: "moi_bridge_1_2days", name: "Moi Bridge (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 380 },
  { id: "molo_overnight", name: "Molo (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 300 },
  { id: "mombasa_buscar", name: "Mombasa (via BusCar 1-2days)", eta: "1-2 Days", maxWeightKg: 10, price: 500 },
  { id: "mombasa_standard_bus", name: "Mombasa (via Dreamline/MashPoa)", eta: "1-2 Days", maxWeightKg: 10, price: 500 },
  { id: "mombasa_2days", name: "Mombasa (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 880 },
  { id: "mombasa_bulk", name: "Mombasa (BULK ORDER via Bus)", eta: "2-3 Days", maxWeightKg: 999, price: 800 },
  { id: "moyale_2days", name: "Moyale (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 2200 },
  { id: "mpeketoni_2days", name: "Mpeketoni (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 2200 },
  { id: "mtito_andei_2days", name: "Mtito Andei (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 750 },
  { id: "mtwapa_bus", name: "Mtwapa (via Bus 1-5days)", eta: "1-5 Days", maxWeightKg: 5, price: 500 },
  { id: "mtwapa_2days", name: "Mtwapa (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 880 },
  { id: "muhoroni_overnight", name: "Muhoroni (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 560 },
  { id: "mukurweini_2_3days", name: "Mukurweini (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 650 },
  { id: "mumias_1_2days", name: "Mumias (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 400 },
  { id: "muranga_2_3days", name: "Murang'a (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 510 },
  { id: "muranga_alternative", name: "Murang’a (Alternative)", eta: "1-2 Days", maxWeightKg: 5, price: 600 },
  { id: "murarandia_2_3days", name: "Murarandia (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 600 },
  { id: "mutomo_2days", name: "Mutomo (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 780 },
  { id: "mwala_1_2days", name: "Mwala (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 600 },
  { id: "mwatate_2days", name: "Mwatate (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 920 },
  { id: "mwea_2_3days", name: "Mwea (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 650 },
  { id: "mwingi_2_3days", name: "Mwingi (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 680 },
  { id: "nairetoi_2days", name: "Nairetoi (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 880 },
  { id: "nairobi_bulk", name: "Nairobi (BULK ORDER via Mololine)", eta: "Same Day", maxWeightKg: 999, price: 500 },
  { id: "nairobi_overnight", name: "Nairobi (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 330 },
  { id: "nairobi_2nk", name: "Nairobi (Pick up at 2NK Matatu)", eta: "Same Day", maxWeightKg: 10, price: 400 },
  { id: "nairobi_mololine", name: "Nairobi (Pick up at Mololine)", eta: "Same Day", maxWeightKg: 10, price: 400 },
  { id: "naivasha_overnight", name: "Naivasha (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 300 },
  { id: "naivasha_molo_group", name: "Naivasha Town (Molo Group 2-3hrs)", eta: "2-3 Hours", maxWeightKg: 8, price: 350 },
  { id: "nakuru_local", name: "Nakuru (HQ Pickup / Delivery)", eta: "Same Day", maxWeightKg: 99, price: 200 },
  { id: "namanga_2days", name: "Namanga (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 760 },
  { id: "nambale_overnight", name: "Nambale (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 550 },
  { id: "nandi_hills_1_2days", name: "Nandi Hills (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 380 },
  { id: "nanyuki_2_3days", name: "Nanyuki (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 700 },
  { id: "nanyuki_matatu", name: "Nanyuki (via 4NTE/2NK Matatu)", eta: "Same Day", maxWeightKg: 5, price: 350 },
  { id: "narok_2days", name: "Narok (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 400 },
  { id: "narok_line", name: "Narok (via Narok Line Matatu)", eta: "Same Day", maxWeightKg: 10, price: 400 },
  { id: "narok_starline", name: "Narok (via Starline Matatu)", eta: "Same Day", maxWeightKg: 10, price: 400 },
  { id: "naromoru_2_3days", name: "Naromoru (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 700 },
  { id: "ngong_nbo", name: "Ngong (NBO)", eta: "1-2 Days", maxWeightKg: 5, price: 450 },
  { id: "njoro_overnight", name: "Njoro (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 300 },
  { id: "nkubu_2_3days", name: "Nkubu (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 750 },
  { id: "nyahururu_overnight", name: "Nyahururu (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 300 },
  { id: "nyali_2_3days", name: "Nyali (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 880 },
  { id: "nyali_dreamline", name: "Nyali (via Dreamline Bus 1-2Days)", eta: "1-2 Days", maxWeightKg: 10, price: 400 },
  { id: "nyali_mashpoa", name: "Nyali (via Mash Poa Bus 1-2Days)", eta: "1-2 Days", maxWeightKg: 10, price: 400 },
  { id: "nyamira_overnight", name: "Nyamira (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 350 },
  { id: "nyeri_2_3days", name: "Nyeri (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 650 },
  { id: "nyeri_matatu", name: "Nyeri (via Matatu 3-4hrs)", eta: "3-4 Hours", maxWeightKg: 5, price: 400 },
  { id: "nzoia_1_2days", name: "Nzoia (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 400 },
  { id: "ogembo_overnight", name: "Ogembo (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 400 },
  { id: "olkalau_1_2days", name: "Olkalau (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 300 },
  { id: "oloitoktok_1_2days", name: "Oloitoktok (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 760 },
  { id: "ongata_rongai", name: "Ongata Rongai (NBO 1-2Days)", eta: "1-2 Days", maxWeightKg: 5, price: 450 },
  { id: "othaya_2_3days", name: "Othaya (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 650 },
  { id: "oyugis_1_2days", name: "Oyugis (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 400 },
  { id: "parklands_nbo", name: "Parklands (NBO)", eta: "Same Day", maxWeightKg: 5, price: 330 },
  { id: "rachuonyo_overnight", name: "Rachuonyo (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 540 },
  { id: "rongo_overnight", name: "Rongo (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 400 },
  { id: "ruaka_mololine", name: "Ruaka (Pick up at Mololine Shuttle)", eta: "Same Day", maxWeightKg: 10, price: 400 },
  { id: "ruiru_overnight", name: "Ruiru (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 550 },
  { id: "rumuruti_2days", name: "Rumuruti (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 350 },
  { id: "runyenjes_2_3days", name: "Runyenjes (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 660 },
  { id: "sabasaba_2_3days", name: "Sabasaba (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 570 },
  { id: "sabatia_overnight", name: "Sabatia (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 420 },
  { id: "sagana_2_3days", name: "Sagana (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 600 },
  { id: "salgaa_overnight", name: "Salgaa (Overnight)", eta: "Overnight", maxWeightKg: 5, price: 300 },
  { id: "siaya_1days", name: "Siaya (1 Days)", eta: "1 Day", maxWeightKg: 5, price: 580 },
  { id: "sirari_easycoach", name: "Sirari (via Easy Coach)", eta: "Overnight", maxWeightKg: 5, price: 500 },
  { id: "sotik_1_2days", name: "Sotik (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 340 },
  { id: "sultan_hamud_2days", name: "Sultan Hamud (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 750 },
  { id: "syokimau_1_2days", name: "Syokimau (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 350 },
  { id: "tala_1_2days", name: "Tala (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 550 },
  { id: "talek_1_2days", name: "Talek (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 550 },
  { id: "taveta_2_3days", name: "Taveta (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 940 },
  { id: "thika_2_3days", name: "Thika (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 550 },
  { id: "thika_matatu", name: "Thika (via Matatu 4NTE/2NK)", eta: "Same Day", maxWeightKg: 10, price: 450 },
  { id: "timau_2_3days", name: "Timau (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 720 },
  { id: "turbo_1_2days", name: "Turbo (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 330 },
  { id: "ugunja_1_2days", name: "Ugunja (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 560 },
  { id: "ukunda_2days", name: "Ukunda (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 900 },
  { id: "voi_2days", name: "Voi (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 750 },
  { id: "voi_bus", name: "Voi (via Bus 2-3days)", eta: "2-3 Days", maxWeightKg: 10, price: 600 },
  { id: "wajir_golden_bus", name: "Wajir (via Golden Bus)", eta: "2-3 Days", maxWeightKg: 5, price: 1150 },
  { id: "watamu_2days", name: "Watamu (2 Days)", eta: "2 Days", maxWeightKg: 5, price: 990 },
  { id: "watamu_bus", name: "Watamu (via BusCar 1-2Days)", eta: "1-2 Days", maxWeightKg: 10, price: 500 },
  { id: "webuye_1_2days", name: "Webuye (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 400 },
  { id: "westlands_nbo", name: "Westlands (NBO)", eta: "Same Day", maxWeightKg: 5, price: 330 },
  { id: "wote_1_2days", name: "Wote (1-2 Days)", eta: "1-2 Days", maxWeightKg: 5, price: 600 },
  { id: "wundanyi_2_3days", name: "Wundanyi (2-3 Days)", eta: "2-3 Days", maxWeightKg: 5, price: 930 }
];